[platformio]
default_envs = seeed_xiao_esp32s3
src_dir = src

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D CAMERA_MODEL_XIAO_ESP32S3

; 默认环境：通过 WiFi OTA 上传（需先串口刷一次带 OTA 的固件）
[env:seeed_xiao_esp32s3]
upload_protocol = espota
upload_port = fpv-car.local

; 应急/首次环境：通过 USB 串口上传
[env:serial]
upload_speed = 460800
upload_protocol = esptool
